# Generated by Django 3.2.8 on 2021-11-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок вывода')),
                ('dont_show_the_post', models.BooleanField(help_text='Есть флаг установлен, проект будет скрыта', verbose_name='Не показывать проект?')),
            ],
            options={
                'verbose_name': 'Тэг публикации',
                'verbose_name_plural': 'Тэги публикаций',
            },
        ),
    ]
