# Generated by Django 3.2.8 on 2021-11-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проект'},
        ),
        migrations.AlterField(
            model_name='project',
            name='dont_show_the_post',
            field=models.BooleanField(help_text='Есть флаг установлен, проект будет скрыт', verbose_name='Не показывать проект?'),
        ),
    ]
