# Generated by Django 3.2.8 on 2021-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211112_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=3, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
