# Generated by Django 3.2.8 on 2021-11-12 08:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211112_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг публикации', 'verbose_name_plural': 'Тэги публикаций'},
        ),
        migrations.AlterField(
            model_name='article',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Превью'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
