# Generated by Django 3.2.8 on 2021-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_dont_show_the_post_article_dont_show_the_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dont_show_the_article',
        ),
        migrations.AddField(
            model_name='article',
            name='dont_show_the_user',
            field=models.BooleanField(default=1, help_text='Есть флаг установлен, пользователь будет скрыт', verbose_name='Не показывать пользователя?'),
            preserve_default=False,
        ),
    ]
