# Generated by Django 3.2.8 on 2021-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20211112_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dont_show_the_user',
        ),
        migrations.AddField(
            model_name='article',
            name='dont_show_the_article',
            field=models.BooleanField(default=1, help_text='Есть флаг установлен, публикация будет скрыта', verbose_name='Не показывать публикацию?'),
            preserve_default=False,
        ),
    ]
