# Generated by Django 3.2.10 on 2021-12-14 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Должность пользователя',
                'verbose_name_plural': 'Должности пользователя',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='dont_show_the_user',
            field=models.BooleanField(default=False, help_text='Есть флаг установлен, пользователь будет скрыт', verbose_name='Не показывать пользователя?'),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок вывода'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование')),
                ('icon', models.CharField(blank=True, help_text='Необходим класс mdi', max_length=50, null=True, verbose_name='Иконка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на социальную сеть')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Социальная сеть пользователя',
                'verbose_name_plural': 'Социальные сети пользователя',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_api.position', verbose_name='Должность'),
        ),
    ]
